# ~/.config/kitty/kitty.conf
# Kitty configuration with the Later This Evening theme and smart titles.

#### FONT SETTINGS ####
font_family      SauceCodePro NF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12


#### THEME ####
include ./theme.conf


#### UI APPEARANCE ####
window_padding_width 15
background_opacity 0.95
background_blur 5
# hide_window_decorations yes

#### CURSOR CUSTOMIZATION ####
cursor_shape block
cursor_blink_interval 0
cursor #fff7f2
cursor_text_color #151517


#### SHELL & BEHAVIOR ####
shell .
allow_remote_control socket-only
listen_on unix:@kitty-rc
scrollback_lines 10000
confirm_os_window_close 0
enable_audio_bell no

# Always use the manual "splits" layout so new windows can be placed explicitly
# (e.g. always vsplit to the right).
#enabled_layouts splits
enabled_layouts splits,stack


enable_keyboard_protocol yes
#### KEYBINDINGS (Minimal & Useful) ####
map ctrl+shift+k clear_terminal scrollback active
map ctrl+equal     change_font_size all +1.0
map ctrl+minus     change_font_size all -1.0
map ctrl+0         change_font_size all 0
map ctrl+shift+h show_scrollback
map ctrl+shift+t new_tab_with_cwd
# Save current kitty session to a fixed file (overwrites).
map ctrl+shift+s save_as_session --save-only --relocatable ~/.local/share/kitty/sessions/last.kitty-session
map ctrl+shift+enter launch --cwd=current --location=split
# Disable kitty split
map ctrl+shift+enter no_op
map ctrl+shift+e     launch --cwd=current --location=vsplit
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down



# Tab bar
tab_bar_margin_width      9
tab_bar_margin_height     9 0
tab_bar_style             slant
tab_bar_min_tabs          1
tab_separator             ""
tab_bar_style powerline
tab_powerline_style angled
tab_title_template              "  {index} {title[title.rfind('/')+1:]}"
active_tab_title_template  "  {index} {title[title.rfind('/')+1:]}"

# Foocolors tab palette
tab_bar_background       #1b1b1d
tab_bar_margin_color     #1b1b1d
active_tab_foreground    #212121
active_tab_background    #5dffe9
active_tab_font_style    bold
inactive_tab_foreground  #bbb4ba
inactive_tab_background  #2d2b32
inactive_tab_font_style  normal
